"""Serialise a Twin to `tier_payload.json`-shaped dict for viewer
compatibility.

The schema match is partial: fields the twin produces (rooms, walls,
ceilings) are emitted with real data; fields not yet generated by the
twin (gaps, dormer_faces, gable_closures, visual_shells, knee_walls,
stairs, story_labels) are emitted as empty lists/defaults so the
existing viewer doesn't crash.

Reads the building's existing tier_payload.json for `classification`
and `address` metadata only — those come from the classify/ layer
which is upstream of the twin and unchanged.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from reconcile_tiers.twin.types import (
    Ceiling,
    CeilingKind,
    Gap,
    Opening,
    RoofSurface,
    Twin,
    Wall,
)


def twin_to_payload(
    twin: Twin, *, source_payload_path: Path | None = None
) -> dict[str, Any]:
    """Convert `twin` to the dict shape the viewer expects.

    `source_payload_path` is the original `tier_payload.json` for this
    building; we read `classification`, `address`, and `build_meta` from
    it. If unset or missing, those fields are emitted as defaults.
    """
    metadata = _metadata(source_payload_path)

    rooms_out: list[dict] = []
    ceiling_out: list[dict] = []
    ceiling_gaps: list[dict] = []

    for wing in twin.building.wings:
        for story in wing.stories:
            for room in story.rooms:
                rooms_out.append(_room_dict(room))
                ceiling_out.extend(_ceiling_dicts(room.ceiling))
                ceiling_gaps.extend(_per_room_ceiling_gaps(room))
        if wing.roof is not None:
            for surface in wing.roof.surfaces:
                ceiling_out.append(_roof_surface_piece(surface))

    return {
        "schema_version": metadata.get("schema_version", "twin-0.1"),
        "uuid": twin.building.uuid,
        "address": metadata.get("address", ""),
        "classification": metadata.get("classification", {}),
        "build_meta": {
            "built_at": metadata.get("build_meta", {}).get("built_at", "twin"),
            "source": "twin",
        },
        "envelope_version": metadata.get("envelope_version", "twin-v0"),
        "story_labels": metadata.get("story_labels", []),
        "building_center": metadata.get("building_center"),
        "rooms": rooms_out,
        "ceiling": ceiling_out,
        "knee_walls": [],
        "dormer_faces": [],
        "gable_closures": [],
        "gaps": [_gap_dict(g) for g in twin.residual.unclaimed_gaps] + ceiling_gaps,
        "stairs": [],
        "visual_shells": [],
        "roof_quality": metadata.get("roof_quality", {}),
    }


def _metadata(source_payload_path: Path | None) -> dict[str, Any]:
    if source_payload_path is None or not source_payload_path.exists():
        return {}
    try:
        return json.loads(source_payload_path.read_text())
    except Exception:
        return {}


def _vec3(v) -> dict:
    return {"x": float(v.x), "y": float(v.y), "z": float(v.z)}


def _quad(corners) -> dict:
    return {"corners": [_vec3(c) for c in corners]}


def _wall_dict(wall: Wall) -> dict:
    # Emit the actual wall polygon — preserves gable peaks, stepped
    # tops, and any non-quad shape extraction surfaced.
    return {
        "corners": [_vec3(c) for c in wall.polygon],
        "descent_strip": None,
        "uplift_strip": None,
        "cutouts": [_opening_quad(op) for op in wall.openings],
        "locator_id": wall.id,
        "synthetic": False,
        "adjacency": "unknown",
    }


def _opening_quad(op: Opening) -> dict:
    return {"corners": [_vec3(c) for c in op.polygon]}


def _room_dict(room) -> dict:
    floor_lid = {
        "corners": [_vec3(c) for c in room.floor.polygon],
        "adjacency": "unknown",
        "holes": [[_vec3(c) for c in hole] for hole in room.floor.holes],
    }
    walls_out = [_wall_dict(w) for w in room.walls]
    doors = [
        _opening_quad(op)
        for w in room.walls
        for op in w.openings
        if op.kind.value == "door"
    ]
    windows = [
        _opening_quad(op)
        for w in room.walls
        for op in w.openings
        if op.kind.value == "window"
    ]
    return {
        "story": room.story_index,
        "locator_id": room.id,
        "floor": [floor_lid],
        "walls": walls_out,
        "doors": doors,
        "windows": windows,
        "heating": None,
    }


def _ceiling_dicts(ceiling: Ceiling) -> list[dict]:
    """Emit only the *canonical* per-room planes for serialisation:
    flat ceilings and flat parts of composite ceilings. Per-room
    OBLIQUE ceilings (and composite oblique parts) are NOT emitted —
    they're per-room slices of a wing-level architectural plane that
    is already represented by the corresponding RoofSurface. Emitting
    both would create overlapping render geometry for the same plane."""
    if ceiling.kind is CeilingKind.FLAT:
        return [_ceiling_piece(ceiling, source_override=None)]
    if ceiling.kind is CeilingKind.OBLIQUE:
        # Single-plane sloped ceiling — its wing RoofSurface IS the
        # canonical representation. Skip emission here.
        return []
    pieces: list[dict] = []
    for part in ceiling.parts:
        if part.kind is CeilingKind.FLAT:
            pieces.append(_ceiling_piece(part, source_override=None))
        # Skip OBLIQUE parts of composite ceilings — wing RoofSurface
        # owns those.
    return pieces


def _per_room_ceiling_gaps(room) -> list[dict]:
    """Compute the regions of the room's floor not covered by any
    candidate ceiling polygon — these are the (x, z) where the
    classifier returns None. Render as `gap_ceiling` entries so the
    viewer surfaces them visibly."""
    from shapely.geometry import Polygon
    from shapely.ops import unary_union

    if len(room.floor.polygon) < 3:
        return []
    floor_y = float(room.floor.polygon[0].y)
    try:
        floor_poly = Polygon([(c.x, c.z) for c in room.floor.polygon]).buffer(0)
    except Exception:
        return []
    if floor_poly.is_empty:
        return []

    ceiling = room.ceiling
    candidate_polys = []
    parts = list(ceiling.parts) if ceiling.parts else [ceiling]
    for part in parts:
        if not part.polygon or len(part.polygon) < 3:
            continue
        try:
            p = Polygon([(c.x, c.z) for c in part.polygon]).buffer(0)
        except Exception:
            continue
        if not p.is_empty:
            candidate_polys.append(p)
    if not candidate_polys:
        ceiling_union = None
    else:
        ceiling_union = unary_union(candidate_polys)

    if ceiling_union is None:
        gap_geom = floor_poly
    else:
        try:
            gap_geom = floor_poly.difference(ceiling_union)
        except Exception:
            return []

    if gap_geom.is_empty:
        return []
    if gap_geom.geom_type == "MultiPolygon":
        candidates = list(gap_geom.geoms)
    elif gap_geom.geom_type == "GeometryCollection":
        # Mixed result: keep only the Polygon members (drop stray
        # lines / points from boundary intersections).
        candidates = [g for g in gap_geom.geoms if g.geom_type == "Polygon"]
    elif gap_geom.geom_type == "Polygon":
        candidates = [gap_geom]
    else:
        return []
    out: list[dict] = []
    for idx, comp in enumerate(candidates):
        if comp.is_empty or comp.area < 0.05:
            continue  # 5cm² minimum — float-precision sliver, not a real gap
        coords = list(comp.exterior.coords)
        if coords and coords[0] == coords[-1]:
            coords = coords[:-1]
        if len(coords) < 3:
            continue
        out.append(
            {
                "corners": [
                    {"x": float(x), "y": float(floor_y), "z": float(z)}
                    for x, z in coords
                ],
                "kind": "gap_ceiling",
                "scope": "room",
                "locator_id": f"{room.id}::ceiling-gap::{idx}",
                "adjacency": "unknown",
            }
        )
    return out


def _gap_dict(gap: Gap) -> dict:
    return {
        "corners": [_vec3(c) for c in gap.polygon],
        "kind": f"gap_{gap.kind.value}",
        "scope": "story",
        "locator_id": gap.id,
        "adjacency": "unknown",
    }


def _roof_surface_piece(surface: RoofSurface) -> dict:
    plane = surface.plane
    return {
        "corners": [_vec3(c) for c in surface.polygon],
        "holes": [],
        "plane": {
            "a": float(plane.a),
            "b": float(plane.b),
            "c": float(plane.c),
            "d": float(plane.d),
        },
        "source": "computed_oblique",
        "arrangement_cell_id": None,
        "locator_id": surface.id,
        "support_quality": 0.0,
        "role": "ceiling",
        "adjacency": "unheatedAttic",
        "merged_from": [],
    }


def _ceiling_piece(ceiling: Ceiling, *, source_override: str | None) -> dict:
    if ceiling.kind is CeilingKind.FLAT:
        source = "flat_ceiling"
    else:
        source = "computed_oblique"
    plane = ceiling.plane
    return {
        "corners": [_vec3(c) for c in ceiling.polygon],
        "holes": [],
        "plane": {
            "a": float(plane.a),
            "b": float(plane.b),
            "c": float(plane.c),
            "d": float(plane.d),
        },
        "source": source_override or source,
        "arrangement_cell_id": None,
        "locator_id": ceiling.id,
        "support_quality": 0.0,
        "role": "ceiling",
        "adjacency": "unknown",
        "merged_from": [],
    }
